### ISSUE TITLE
teamviewer userless computer but still approval

### ISSUE THREAD

**Issue by kornflex** [MicrosoftDocs/memdocs.fr-fr#1]
My computer has been enrolled with DEM user.

I can see it as " shared computer" in office portal.
No primary user is shown on intune.

But, I still have the approval with teamviewer.

**Comment by srvbpigh** [comment]
Hello, @kornflex
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kornflex 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
